# Generated by Django 2.0.6 on 2018-09-18 20:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_ml', models.IntegerField(max_length=64)),
                ('status_ma', models.IntegerField(max_length=64)),
                ('seniority', models.IntegerField(max_length=16)),
                ('home', models.IntegerField(max_length=8)),
                ('time', models.IntegerField(max_length=64)),
                ('age', models.IntegerField(max_length=64)),
                ('marital', models.IntegerField(max_length=8)),
                ('records', models.IntegerField(max_length=32)),
                ('job', models.IntegerField(max_length=32)),
                ('expenses', models.IntegerField(max_length=64)),
                ('income', models.IntegerField(max_length=64)),
                ('assets', models.IntegerField(max_length=16)),
                ('debt', models.IntegerField(max_length=64)),
                ('amount', models.IntegerField(max_length=64)),
                ('price', models.IntegerField(max_length=64)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Consumer')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(max_length=16)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Consumer')),
            ],
        ),
    ]
