# Generated by Django 2.0.6 on 2018-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20180918_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='age',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='assets',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='debt',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='expenses',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='home',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='income',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='job',
            field=models.IntegerField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='marital',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='price',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='records',
            field=models.IntegerField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='seniority',
            field=models.IntegerField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status_ma',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status_ml',
            field=models.IntegerField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='time',
            field=models.IntegerField(default=0, max_length=64),
        ),
    ]
